### ISSUE TITLE
bug: could not open cortex binary if username contains a special character

### ISSUE THREAD

**Issue by louis-jan** [janhq/cortex.cpp#1724]
### Cortex version

1.0.3

### Describe the issue and expected behaviour

Can not open cortex-server.cpp when it is placed in a folder whose path contains a special character, such as: `C:\Users\lephi\Desktop\Alguém` 

### Steps to Reproduce

1. Create a folder with name `Alguém` and put cortex-server.cpp bin file in.
2. Create config file with this content 
```yaml
logFolderPath: C:\Users\lephi\Desktop\Alguém
logLlamaCppPath: ./logs/cortex.log
logTensorrtLLMPath: ./logs/cortex.log
logOnnxPath: ./logs/cortex.log
dataFolderPath: C:\Users\lephi\Desktop\Alguém
maxLogLines: 100000
apiServerHost: 127.0.0.1
apiServerPort: 39291
checkedForUpdateAt: 0
checkedForLlamacppUpdateAt: 0
latestRelease: default_version
latestLlamacppRelease: ""
huggingFaceToken: ""
gitHubUserAgent: ""
gitHubToken: ""
llamacppVariant: windows-amd64-avx2-cuda-12-0
llamacppVersion: v0.1.39
enableCors: true
allowedOrigins:
  - http://localhost:39281
  - http://127.0.0.1:39281
  - http://0.0.0.0:39281
proxyUrl: ""
verifyProxySsl: true
verifyProxyHostSsl: true
proxyUsername: ""
proxyPassword: ""
noProxy: example.com,::1,localhost,127.0.0.1
verifyPeerSsl: false
verifyHostSsl: true
```
3. Try open by double-clicking.

### What is your OS?

- [X] Windows
- [ ] Mac Silicon
- [ ] Mac Intel
- [ ] Linux / Ubuntu

### What engine are you running?

- [ ] cortex.llamacpp (default)
- [ ] cortex.tensorrt-llm (Nvidia GPUs)
- [ ] cortex.onnx (NPUs, DirectML)
