### ISSUE TITLE
feat: Cache model and engine downloads so users can restart download

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex.cpp#777]
**Problem:**
1. cortex run trt/onnx model
2. wait for download
3. 10 minutes in, something might happen, internet drops/windows goes to sleep, etc.
4. Lose entire download progress.
5. Sadness

Happened for me 2/3 times for larger model folders

**Suggested solution**
- cache downloads, host a mirror, open to better suggestions

**Comment by freelerobot** [comment]
Related issues: 
- [x] https://github.com/janhq/cortex.cpp/issues/1139
- [x] https://github.com/janhq/cortex.cpp/issues/1017
- [ ] https://github.com/janhq/cortex.cpp/issues/1010
- [ ] https://github.com/janhq/jan/issues/3519

Related discussion: 
https://github.com/janhq/cortex.cpp/discussions/1129

**Comment by dan-menlo** [comment]
Linking this to main issue #1077

**Comment by hiento09** [comment]
Hien will help to add checksum and version to cortex.tensorrtllm, cortex.llamacpp, cortex.onnx

**Comment by namchuai** [comment]
proposed:
file name: `version.txt`
content: yaml compatible
```
name: full_name (vulkan/os/arch for us to troubleshoot issue in the future)
version: x.y.z
description: (optional)
```

**Comment by hiento09** [comment]
For `checksum.yml` file, use format similar to Jan app
Content: yaml compatible
```
version: 0.5.3
files:
  - url: jan-mac-arm64-0.5.3.zip
    sha512: >-
      GE3eaRoDi/fuqzdC0SQBvKvwjPGVPPBeulCo4JkjZuZ+0FLx0AiT/LgoUIMiOLh5LSR0Q73emkMsSBIcQco4bg==
  - url: jan-mac-arm64-0.5.3.dmg
    sha512: >-
      bpB8x0UajDWvshJ37NmuQVLl9MqUd3J/7yydKWtpuEJBsu2TxXB8qJSta1mvxXGBke7SS13V2y3syP/qerHvoA==
  - url: jan-mac-x64-0.5.3.zip
    sha512: >-
      oX0mTvuqshXoy3TEVmw+JQGJaeJK//42j+UL6VTJus/637LeLzf3m/8TtIZMe7Ac6k5zpTox8bWqjIz5mKp6Bg==
  - url: jan-mac-x64-0.5.3.dmg
    sha512: >-
      Hd9SPyJM9TL2CVG0Is4lQzCSAXcn4WhVmra6hSBx0PgVN9L6utdc+yiYnhtd1L6x9BR1mwlZ3UCSJ8Ffr1wwJA==
```
